name: Android CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.9
    - uses: actions/setup-java@v1
    - name: Build with Gradle
      with:
        java-version: 1.9
    - run: ./gradlew build jacocoTestReport
