name: Android CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.9
      uses: actions/setup-java@v1
      with:
        java-version: 1.9
    - name: Build with Gradle
    - run: ./gradlew build jacocoTestReport
    - run: mkdir -p artifacts
    - run: cat app/build/reports/jacocoTestDebugUnitTestReport/html/index.html > artifacts/jacoco.html
  - uses: actions/upload-artifact@v1
    with:
      name: reports
      path: artifacts
